### PR TITLE
Fix/161 add title to column comp

### LINKED ISSUE #161: Add column with names for player comparison

### PR DESCRIPTION
**Pull request by melisa-abuin**
Automatically detected issues: Closes #161

### CODE REVIEW

File: components/molecules/columns/index.tsx [hunk 1]
```diff
@@ -1,53 +1,52 @@
...
+                >
+                  {value || 0}
+                </TextWithIcon>
+                <Description highlight={highlight}>{description}</Description>
+              </Col>
+            ))}
+          </Row>
+        </Row>
       ))}
+
```
Comment (melisa-abuin) [inline components/molecules/columns/index.tsx:49]: remove

File: utils/formatComparePlayer/index.tsx [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+
+/**
+ * Format the data of two players and provide a comparison by category requested
+ * @param player
+ * @param comparePlayer
+ * @param columns
+ * @param difficulty
+ * @returns
+ */
+export const formatComparePlayer = (
```
Comment (melisa-abuin) [inline utils/formatComparePlayer/index.tsx:34]: test

File: components/molecules/columns/index.tsx [hunk 3]
```diff
@@ -1,53 +1,52 @@
 'use client'
```
Comment (melisa-abuin) [inline components/molecules/columns/index.tsx:1]: update tests
